### ISSUE TITLE
Function annotation not working for schematics type

### ISSUE THREAD

**Issue by greenj5** [toumorokoshi/transmute-core#10]
`transmute_core.exceptions.SerializationException: unable to create json schema for type <class 'schematics.types.base.UUIDType'>. Expected a primitive or  a schematics model or type`

**Comment by toumorokoshi** [comment]
This is now fixed, as of 1.0.1.

The main issue is that it's not possible to pass in a Type class from schematics: A type object is required. 

transmute now accepts a schematics type, and will handle instantiating it silently.
