### ISSUE TITLE
Returning custom headers and using the whole request body as the argument to the function

### ISSUE THREAD

**Issue by rvangraan** [toumorokoshi/transmute-core#21]
Hi,

I want to 

1. create a method that accepts a single structure of a certain type and
2. returns a `Location` header with status code 201 

i.e. something like this:
```
class Person(Model):
    firstName = StringType()
    lastName = StringType()
    title = StringType()

 @aiohttp_transmute.describe(
        methods='POST',
        paths=URLs.person,
        response_types={
            201: {
                'description': 'Created',
                'headers': [
                    {'Location': {'type': 'url',
                                  'description': 'A reference to the newly created Person'
                                  }
                     }
                ],
                'type': Person
            }
        }
    )
    async def person_create(self, body: GenericParty):
        return Response(
            ...
        )

```

So I want to body of the request to be:
```
{ 
  "firstName": ...,
  "lastName": ...,
  ...
}
```
i.e. I want the whole body to be passed to the function, rather than each named parameter. I tried the above, but the Swagger generated looks like this:

```
{
  "body": { 
      "firstName": ...,
      "lastName": ...,
      ...
    }
}
```
How can I do this? (I've searched the repo and I don't see any examples of customer header responses).

For reference, this is the swagger I'm looking for:
```
paths:
  /person:
    post:
      summary: Creates a new person record.
      responses:
        201:
          description: Created
          schema:
             $ref: "#/definitions/Person"
          headers:
            Location:
              type: url
              description: Location of the new person
```
Thanks

**Comment by toumorokoshi** [comment]
It sounds like there's two separate behaviors you're looking for. The summary is those aren't supported right now, but I can add them. 

1. Returning back headers.

There is no explicit functionality for that yet. But I could imagine something like:

```
@aiohttp_transmute.describe(
        methods='POST',
        paths=URLs.person,
        response_types={
            201: {
                'description': 'Created',
                'headers': {
                    'Location': { 'type': 'string', 'format': 'url', 'description': 'A reference to the newly created Person'}
                },
                'type': Person
            }
        }
    )
async def myfunc():
    return Response(True, headers={"location": "http://my-location.com/path"})
```
Basically what you've already described, sans the enclosing list. 

2. Declaring a single schema for a parameter set (like body)

This is already a proposal in #8, and we can probably pick up the discussion there.

Thoughts on these?

**Comment by rvangraan** [comment]
@toumorokoshi yes thank you. The header syntax makes perfect sense.

**Comment by toumorokoshi** [comment]
cool! there's no support to modify headers in responses in the transmute implementations, so this will require some retooling. 

working on a 2.0 branch to support this case as well.

**Comment by toumorokoshi** [comment]
@rvangraan this now exists in transmute-core 1.4.0. I modified the way a header type is specified, so it just uses the same schematics / primitive typing stuff that everything else does:

http://transmute-core.readthedocs.io/en/latest/function.html#headers-in-a-response

Regarding your specific case where you want to clarify that the type is a url, you can pass in schematics URLType, which ends up with the schema `{"type": "string", "format": "url"}`

https://github.com/toumorokoshi/transmute-core/blob/master/transmute_core/tests/test_schematics.py#L63

give that a try and let me know if that satisfies your issues. This functinoality is provided for aiohttp-transmute an flask-transmute.

**Comment by rvangraan** [comment]
Thanks - I'll give it a try.
