### ISSUE TITLE
Swagger UI not working

### ISSUE THREAD

**Issue by rvangraan** [toumorokoshi/transmute-core#25]
Hi,

Since the last set of updates the built-in Swagger UI tool stopped working. It still loads, but it has no content. 
![screen shot 2017-05-30 at 12 30 58](https://cloud.githubusercontent.com/assets/2574318/26581326/e4118d16-4533-11e7-9321-697abb141742.png)
(The JSON link is still working)

**Comment by toumorokoshi** [comment]
@rvangraan I'm attempting to repro, and can't seem to. All apps I've tested seem to be showing fine.

Can you pull up a console debugger in your browser and see if there are any errors? The last time I saw this, there was a parsing bug in the swagger ui.

I've tried this with flask and aiohttp. 

<img width="992" alt="screen shot 2017-05-30 at 8 12 53 pm" src="https://cloud.githubusercontent.com/assets/391240/26614360/b6cda150-4574-11e7-9ffc-c925492be3eb.png">

**Comment by rvangraan** [comment]
hey,

Yes loads of errors:

![screen shot 2017-05-31 at 06 58 00](https://cloud.githubusercontent.com/assets/2574318/26617725/a548e5ac-45ce-11e7-9ca8-d7d59fbbb3dd.png)

**Comment by rvangraan** [comment]
Perhaps the way this is supposed to start changed? We're doing this:
```
            swagger_handler = aiohttp_transmute.create_swagger_json_handler(app)
            app.router.add_route('GET', '{}/swagger.json'.format(service_root_url), swagger_handler)
            aiohttp_transmute.add_swagger_api_route(app,
                                                    '{}/swagger'.format(service_root_url),
                                                    '{}/swagger.json'.format(service_root_url))
```

**Comment by toumorokoshi** [comment]
No, no code changes on the swagger UI. Also tested it clean with the attached examples and the /swagger page is returning proper UI.

```
from aiohttp import web
import aiohttp_transmute

@aiohttp_transmute.describe(paths="/customers/{name}")
async def multiply(request, name: str, left: int, right: int) -> int:
    return left + right

@aiohttp_transmute.describe(methods="POST", paths="/customers/{name}")
async def multiply_post(request, name: str, left: int, right: int) -> int:
    return left + right

app = web.Application()
aiohttp_transmute.route(app, multiply)
aiohttp_transmute.route(app, multiply_post)
service_root_url = ""
swagger_handler = aiohttp_transmute.create_swagger_json_handler(app)
app.router.add_route('GET', '{}/swagger.json'.format(service_root_url), swagger_handler)
aiohttp_transmute.add_swagger_api_route(app,
                                        '{}/swagger'.format(service_root_url),
                                        '{}/swagger.json'.format(service_root_url))
web.run_app(app)  # runs on http://localhost:8080/swagger
```


The errors indicate that the app itself can't find the resource at those urls. Those give me two thoughts:

1. the statics don't exist in your installation. You can check this by looking in your site-packages directory: there should be statics under tranmsute_core/swagger/statics/

I've verified that the newest transmute core tar and whl packages have this, and installations shows them as well.

2. the app attaches other resources later which override the /_swagger directory that gets mounted. Maybe it's a subapp or something that gets mounted on root? Are there any other routes added in your application after mounting the swagger routes which might be overriding root paths in some way?

3. if both 1 and 2 are ok, can you try switching to an older version of transmute-core and let me know the newest version that you don't see this issue?

As an aside, there's a shorthand for adding the swagger json and the html all at once. just a more convenient call maybe once we've figured this out:

`aiohttp_transmute.add_swagger(app, "/swagger.json", "/swagger")`

**Comment by rvangraan** [comment]
Thanks - I'll have a look tonight.

**Comment by rvangraan** [comment]
Hi,

It looks like the static directory layout has changed. The one on my file system looks like this:
```
ls -al ./venv/lib/python3.5/site-packages/transmute_core/swagger/static
total 6136
drwxr-xr-x  11 rvg  staff      374 29 May 12:12 .
drwxr-xr-x   7 rvg  staff      238 29 May 12:12 ..
drwxr-xr-x   7 rvg  staff      238 29 May 12:12 css
drwxr-xr-x   4 rvg  staff      136 29 May 12:12 fonts
drwxr-xr-x  12 rvg  staff      408 29 May 12:12 images
-rw-r--r--   1 rvg  staff     4246 29 May 12:12 index.html
drwxr-xr-x  17 rvg  staff      578 29 May 12:12 lang
-rw-r--r--   1 rvg  staff      489 29 May 12:12 o2c.html
drwxr-xr-x  24 rvg  staff      816 29 May 12:12 swagger-ui-2.2.8
-rw-r--r--   1 rvg  staff  2678202 29 May 12:12 swagger-ui.js
-rw-r--r--   1 rvg  staff   447732 29 May 12:12 swagger-ui.min.js
```
The `lib` directory the browser is trying to access doesn't exist.

**Comment by toumorokoshi** [comment]
@rvangraan ok! I think I figured it out. 

You must be installing from the master branch. It looks like some gitignore rules I put into place caused the lib directory of the statics to not be added.

I've verified the previous head didn't work, added libs, and verified they are now in the new head commit.

Thanks for sticking with it! Give it a try now.

**Comment by toumorokoshi** [comment]
reopening until issue is verified externally.

**Comment by rvangraan** [comment]
Hi there,

Tried again and the UI is back. 

Thanks!
