### ISSUE TITLE
Is there a way to have optional arguments in a request

### ISSUE THREAD

**Issue by pumelo** [toumorokoshi/transmute-core#3]
As long as I can see, the only way is to have "optional" arguments is to defined them and in the request send them as an empty string....
Otherwise the server will answer with
`"result": "invalid api use: required arguments ['xxx'] not passed"`

Am I missing something or is it really not possible to have optional arguments?

Actually the above message comes from aiohttp-transmute. However, the limitation is more related to the core library then to asyncio thats why I'm asking here.. =)

**Comment by toumorokoshi** [comment]
transmute-core does support optional values (just use keyword arguments), but looks like it wasn't documented. I just pushed a change that should document that now:

http://transmute-core.readthedocs.io/en/latest/routes.html#optional-values

Whether that's honored or not, however, is dependent on the framework-specific toolkit. But it looks like that works for aiohttp-transmute:

https://github.com/toumorokoshi/aiohttp-transmute/blob/master/aiohttp_transmute/tests/example.py#L23
https://github.com/toumorokoshi/aiohttp-transmute/blob/master/aiohttp_transmute/tests/test_full.py#L42

Can you try that and see if that works for you?

**Comment by pumelo** [comment]
Thank you for your fast answer and for publishing the usage in the documentation, this is what I was looking for.
