### ISSUE TITLE
Feature request: Allow specifying parameter descriptions

### ISSUE THREAD

**Issue by stephenk-zillow** [toumorokoshi/transmute-core#37]
Currently there does not seem to be a facility for specifying parameter description text in either flask-transmute or transmute-core. It would be convenient if this functionality were supported.

**Comment by toumorokoshi** [comment]
I think this isn't hard to add. I could imagine a new decorator that works something like:

```
from transmute_core import parameter_description

@parameter_data({"left": "this is the left operand", "right": "this is the right operand"})
def add(left: int, right: int) -> int:
```

thoughts? I'm looking for a more fluid way to add this, but this is a minimal piece of plumbing that could be added for now.

**Comment by toumorokoshi** [comment]
parameter descriptions are added!
