### ISSUE TITLE
Update to swagger-ui 3.x

### ISSUE THREAD

**Issue by LucidOne** [toumorokoshi/transmute-core#43]
I think the static files here
https://github.com/toumorokoshi/transmute-core/tree/master/transmute_core/swagger/static
need to be updated from here
https://github.com/swagger-api/swagger-ui/tree/master/dist

**Comment by toumorokoshi** [comment]
we are now using swagger 3.0's UI! But OpenAPI 3.0 is not yet used to publish the definitions.

**Comment by LucidOne** [comment]
Thanks!

**Comment by Nichaka** [comment]
Any ETA to support OpenAPI 3.0? Thanks.

**Comment by toumorokoshi** [comment]
> Any ETA to support OpenAPI 3.0? Thanks.

Hi! This library currently isn't under active development, so unfortunately no plans to support OpenAPI 3.0

But I [created a tracking ticket](https://github.com/toumorokoshi/transmute-core/issues/53) with help wanted in case anyone would like to contribute.
